version: '3'
volumes:
  postgresql_data: {}
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'POSTGRESQL_PASSWORD=123'
      - 'POSTGRESQL_USERNAME=postgres'
      - 'POSTGRESQL_DATABASE=testdb'

  crud-api:
    hostname: crud-api
    restart: always
    ports:
    - 8080:80
    logging:
      driver: "json-file"
      options: 
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    #image: "asia-southeast1-docker.pkg.dev/devops-skills-sharing/skilllane/skilllane-crud-demo:develop-1dd4dc4"
    build:
      context: .
      dockerfile: Dockerfile
