version: '3'
volumes:
  pgsql: {}
services:
  crud-api:
    hostname: crud-api
    restart: always
    ports:
    - 8080:80
    logging:
      driver: "json-file"
      options: 
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    image: "asia-southeast1-docker.pkg.dev/devops-skills-sharing/skilllane/skilllane-crud-demo:develop-1dd4dc4"
    #build:
    #  context: .
    #  dockerfile: Dockerfile
